# Импорт основных окон
from .welcome_window import WelcomeWindow
from .registration_window import RegistrationWindow
from .main_window import MainWindow
from .basket_window import Oformalenie_Zakaza
from .balance_window import Poplnenie_balansa
from .admin_window import SetingForAdmin
from .worker_window import SetingForWorkers
from .product_dialog import AddProductDialog
