# Импорт основных окон
from .admin_window import AdminWindow
from .balance_window import AddBalance
from .basket_window import BasketWindow
from .info_window import InfoWindow
from .main_window import MainWindow
from .registration_window import RegistrationWindow
from .welcome_window import WelcomeWindow
from .worker_window import WorkerWindow
